const types = {
    PROVIDER_LOADED: 'PROVIDER_LOADED',
    NETWORK_LOADED: 'NETWORK_LOADED',
    ACCOUNT_LOADED: 'ACCOUNT_LOADED',
    EXCHANGE_LOADED: 'EXCHANGE_LOADED',
    TOKEN_1_LOADED: 'TOKEN_1_LOADED',
    TOKEN_2_LOADED: 'TOKEN_2_LOADED',
    ETHER_BALANCE_LOADED: 'ETHER_BALANCE_LOADED'
}

export default types