const types = {
    PROVIDER_LOADED: 'PROVIDER_LOADED',
    NETWORK_LOADED: 'NETWORK_LOADED',
    ACCOUNT_LOADED: 'ACCOUNT_LOADED',
    EXCHANGE_LOADED: 'EXCHANGE_LOADED',
    TOKEN_1_LOADED: 'TOKEN_1_LOADED',
    TOKEN_2_LOADED: 'TOKEN_2_LOADED',
    ETHER_BALANCE_LOADED: 'ETHER_BALANCE_LOADED',
    TOKEN_1_BALANCE_LOADED: 'TOKEN_1_BALANCE_LOADED',
    TOKEN_2_BALANCE_LOADED: 'TOKEN_2_BALANCE_LOADED',
    EXCHANGE_TOKEN_1_BALANCE_LOADED: 'EXCHANGE_TOKEN_1_BALANCE_LOADED',
    EXCHANGE_TOKEN_2_BALANCE_LOADED: 'EXCHANGE_TOKEN_2_BALANCE_LOADED',
    TRANSFER_REQUEST: 'TRANSFER_REQUEST',
    TRANSFER_SUCCESS: 'TRANSFER_SUCCESS',
    TRANSFER_FAIL: 'TRANSFER_FAIL',
    NEW_ORDER_REQUEST: 'NEW_ORDER_REQUEST',
    NEW_ORDER_SUCCESS: 'NEW_ORDER_SUCCESS',
    NEW_ORDER_FAIL: 'NEW_ORDER_FAIL',
    ALL_ORDERS_LOADED: 'ALL_ORDERS_LOADED',
    CANCELLED_ORDERS_LOADED: 'CANCELLED_ORDERS_LOADED',
    FILLED_ORDERS_LOADED: 'FILLED_ORDERS_LOADED',
}

export default types